# *******************************************************
# *** This is a generated file from project duplicity ***
# ***                 DO NOT MODIFY!                  ***
# *** Use tools/make_gpg_error_codes.py to update.    ***
# *******************************************************

gpg_error_codes = {
    0: u'GPG_ERR_NO_ERROR: Success',
    1: u'GPG_ERR_GENERAL: General error',
    2: u'GPG_ERR_UNKNOWN_PACKET: Unknown packet',
    3: u'GPG_ERR_UNKNOWN_VERSION: Unknown version in packet',
    4: u'GPG_ERR_PUBKEY_ALGO: Invalid public key algorithm',
    5: u'GPG_ERR_DIGEST_ALGO: Invalid digest algorithm',
    6: u'GPG_ERR_BAD_PUBKEY: Bad public key',
    7: u'GPG_ERR_BAD_SECKEY: Bad secret key',
    8: u'GPG_ERR_BAD_SIGNATURE: Bad signature',
    9: u'GPG_ERR_NO_PUBKEY: No public key',
    10: u'GPG_ERR_CHECKSUM: Checksum error',
    11: u'GPG_ERR_BAD_PASSPHRASE: Bad passphrase',
    12: u'GPG_ERR_CIPHER_ALGO: Invalid cipher algorithm',
    13: u'GPG_ERR_KEYRING_OPEN: Cannot open keyring',
    14: u'GPG_ERR_INV_PACKET: Invalid packet',
    15: u'GPG_ERR_INV_ARMOR: Invalid armor',
    16: u'GPG_ERR_NO_USER_ID: No user ID',
    17: u'GPG_ERR_NO_SECKEY: No secret key',
    18: u'GPG_ERR_WRONG_SECKEY: Wrong secret key used',
    19: u'GPG_ERR_BAD_KEY: Bad session key',
    20: u'GPG_ERR_COMPR_ALGO: Unknown compression algorithm',
    21: u'GPG_ERR_NO_PRIME: Number is not prime',
    22: u'GPG_ERR_NO_ENCODING_METHOD: Invalid encoding method',
    23: u'GPG_ERR_NO_ENCRYPTION_SCHEME: Invalid encryption scheme',
    24: u'GPG_ERR_NO_SIGNATURE_SCHEME: Invalid signature scheme',
    25: u'GPG_ERR_INV_ATTR: Invalid attribute',
    26: u'GPG_ERR_NO_VALUE: No value',
    27: u'GPG_ERR_NOT_FOUND: Not found',
    28: u'GPG_ERR_VALUE_NOT_FOUND: Value not found',
    29: u'GPG_ERR_SYNTAX: Syntax error',
    30: u'GPG_ERR_BAD_MPI: Bad MPI value',
    31: u'GPG_ERR_INV_PASSPHRASE: Invalid passphrase',
    32: u'GPG_ERR_SIG_CLASS: Invalid signature class',
    33: u'GPG_ERR_RESOURCE_LIMIT: Resources exhausted',
    34: u'GPG_ERR_INV_KEYRING: Invalid keyring',
    35: u'GPG_ERR_TRUSTDB: Trust DB error',
    36: u'GPG_ERR_BAD_CERT: Bad certificate',
    37: u'GPG_ERR_INV_USER_ID: Invalid user ID',
    38: u'GPG_ERR_UNEXPECTED: Unexpected error',
    39: u'GPG_ERR_TIME_CONFLICT: Time conflict',
    40: u'GPG_ERR_KEYSERVER: Keyserver error',
    41: u'GPG_ERR_WRONG_PUBKEY_ALGO: Wrong public key algorithm',
    42: u'GPG_ERR_TRIBUTE_TO_D_A: Tribute to D. A.',
    43: u'GPG_ERR_WEAK_KEY: Weak encryption key',
    44: u'GPG_ERR_INV_KEYLEN: Invalid key length',
    45: u'GPG_ERR_INV_ARG: Invalid argument',
    46: u'GPG_ERR_BAD_URI: Syntax error in URI',
    47: u'GPG_ERR_INV_URI: Invalid URI',
    48: u'GPG_ERR_NETWORK: Network error',
    49: u'GPG_ERR_UNKNOWN_HOST: Unknown host',
    50: u'GPG_ERR_SELFTEST_FAILED: Selftest failed',
    51: u'GPG_ERR_NOT_ENCRYPTED: Data not encrypted',
    52: u'GPG_ERR_NOT_PROCESSED: Data not processed',
    53: u'GPG_ERR_UNUSABLE_PUBKEY: Unusable public key',
    54: u'GPG_ERR_UNUSABLE_SECKEY: Unusable secret key',
    55: u'GPG_ERR_INV_VALUE: Invalid value',
    56: u'GPG_ERR_BAD_CERT_CHAIN: Bad certificate chain',
    57: u'GPG_ERR_MISSING_CERT: Missing certificate',
    58: u'GPG_ERR_NO_DATA: No data',
    59: u'GPG_ERR_BUG: Bug',
    60: u'GPG_ERR_NOT_SUPPORTED: Not supported',
    61: u'GPG_ERR_INV_OP: Invalid operation code',
    62: u'GPG_ERR_TIMEOUT: Timeout',
    63: u'GPG_ERR_INTERNAL: Internal error',
    64: u'GPG_ERR_EOF_GCRYPT: EOF (gcrypt)',
    65: u'GPG_ERR_INV_OBJ: Invalid object',
    66: u'GPG_ERR_TOO_SHORT: Provided object is too short',
    67: u'GPG_ERR_TOO_LARGE: Provided object is too large',
    68: u'GPG_ERR_NO_OBJ: Missing item in object',
    69: u'GPG_ERR_NOT_IMPLEMENTED: Not implemented',
    70: u'GPG_ERR_CONFLICT: Conflicting use',
    71: u'GPG_ERR_INV_CIPHER_MODE: Invalid cipher mode',
    72: u'GPG_ERR_INV_FLAG: Invalid flag',
    73: u'GPG_ERR_INV_HANDLE: Invalid handle',
    74: u'GPG_ERR_TRUNCATED: Result truncated',
    75: u'GPG_ERR_INCOMPLETE_LINE: Incomplete line',
    76: u'GPG_ERR_INV_RESPONSE: Invalid response',
    77: u'GPG_ERR_NO_AGENT: No agent running',
    78: u'GPG_ERR_AGENT: Agent error',
    79: u'GPG_ERR_INV_DATA: Invalid data',
    80: u'GPG_ERR_ASSUAN_SERVER_FAULT: Unspecific Assuan server fault',
    81: u'GPG_ERR_ASSUAN: General Assuan error',
    82: u'GPG_ERR_INV_SESSION_KEY: Invalid session key',
    83: u'GPG_ERR_INV_SEXP: Invalid S-expression',
    84: u'GPG_ERR_UNSUPPORTED_ALGORITHM: Unsupported algorithm',
    85: u'GPG_ERR_NO_PIN_ENTRY: No pinentry',
    86: u'GPG_ERR_PIN_ENTRY: pinentry error',
    87: u'GPG_ERR_BAD_PIN: Bad PIN',
    88: u'GPG_ERR_INV_NAME: Invalid name',
    89: u'GPG_ERR_BAD_DATA: Bad data',
    90: u'GPG_ERR_INV_PARAMETER: Invalid parameter',
    91: u'GPG_ERR_WRONG_CARD: Wrong card',
    92: u'GPG_ERR_NO_DIRMNGR: No dirmngr',
    93: u'GPG_ERR_DIRMNGR: dirmngr error',
    94: u'GPG_ERR_CERT_REVOKED: Certificate revoked',
    95: u'GPG_ERR_NO_CRL_KNOWN: No CRL known',
    96: u'GPG_ERR_CRL_TOO_OLD: CRL too old',
    97: u'GPG_ERR_LINE_TOO_LONG: Line too long',
    98: u'GPG_ERR_NOT_TRUSTED: Not trusted',
    99: u'GPG_ERR_CANCELED: Operation cancelled',
    100: u'GPG_ERR_BAD_CA_CERT: Bad CA certificate',
    101: u'GPG_ERR_CERT_EXPIRED: Certificate expired',
    102: u'GPG_ERR_CERT_TOO_YOUNG: Certificate too young',
    103: u'GPG_ERR_UNSUPPORTED_CERT: Unsupported certificate',
    104: u'GPG_ERR_UNKNOWN_SEXP: Unknown S-expression',
    105: u'GPG_ERR_UNSUPPORTED_PROTECTION: Unsupported protection',
    106: u'GPG_ERR_CORRUPTED_PROTECTION: Corrupted protection',
    107: u'GPG_ERR_AMBIGUOUS_NAME: Ambiguous name',
    108: u'GPG_ERR_CARD: Card error',
    109: u'GPG_ERR_CARD_RESET: Card reset required',
    110: u'GPG_ERR_CARD_REMOVED: Card removed',
    111: u'GPG_ERR_INV_CARD: Invalid card',
    112: u'GPG_ERR_CARD_NOT_PRESENT: Card not present',
    114: u'GPG_ERR_NOT_CONFIRMED: Not confirmed',
    115: u'GPG_ERR_CONFIGURATION: Configuration error',
    116: u'GPG_ERR_NO_POLICY_MATCH: No policy match',
    117: u'GPG_ERR_INV_INDEX: Invalid index',
    118: u'GPG_ERR_INV_ID: Invalid ID',
    119: u'GPG_ERR_NO_SCDAEMON: No SmartCard daemon',
    120: u'GPG_ERR_SCDAEMON: SmartCard daemon error',
    121: u'GPG_ERR_UNSUPPORTED_PROTOCOL: Unsupported protocol',
    122: u'GPG_ERR_BAD_PIN_METHOD: Bad PIN method',
    123: u'GPG_ERR_CARD_NOT_INITIALIZED: Card not initialized',
    124: u'GPG_ERR_UNSUPPORTED_OPERATION: Unsupported operation',
    125: u'GPG_ERR_WRONG_KEY_USAGE: Wrong key usage',
    126: u'GPG_ERR_NOTHING_FOUND: Nothing found',
    127: u'GPG_ERR_WRONG_BLOB_TYPE: Wrong blob type',
    128: u'GPG_ERR_MISSING_VALUE: Missing value',
    129: u'GPG_ERR_HARDWARE: Hardware problem',
    130: u'GPG_ERR_PIN_BLOCKED: PIN blocked',
    131: u'GPG_ERR_USE_CONDITIONS: Conditions of use not satisfied',
    132: u'GPG_ERR_PIN_NOT_SYNCED: PINs are not synced',
    133: u'GPG_ERR_INV_CRL: Invalid CRL',
    134: u'GPG_ERR_BAD_BER: BER error',
    135: u'GPG_ERR_INV_BER: Invalid BER',
    136: u'GPG_ERR_ELEMENT_NOT_FOUND: Element not found',
    137: u'GPG_ERR_IDENTIFIER_NOT_FOUND: Identifier not found',
    138: u'GPG_ERR_INV_TAG: Invalid tag',
    139: u'GPG_ERR_INV_LENGTH: Invalid length',
    140: u'GPG_ERR_INV_KEYINFO: Invalid key info',
    141: u'GPG_ERR_UNEXPECTED_TAG: Unexpected tag',
    142: u'GPG_ERR_NOT_DER_ENCODED: Not DER encoded',
    143: u'GPG_ERR_NO_CMS_OBJ: No CMS object',
    144: u'GPG_ERR_INV_CMS_OBJ: Invalid CMS object',
    145: u'GPG_ERR_UNKNOWN_CMS_OBJ: Unknown CMS object',
    146: u'GPG_ERR_UNSUPPORTED_CMS_OBJ: Unsupported CMS object',
    147: u'GPG_ERR_UNSUPPORTED_ENCODING: Unsupported encoding',
    148: u'GPG_ERR_UNSUPPORTED_CMS_VERSION: Unsupported CMS version',
    149: u'GPG_ERR_UNKNOWN_ALGORITHM: Unknown algorithm',
    150: u'GPG_ERR_INV_ENGINE: Invalid crypto engine',
    151: u'GPG_ERR_PUBKEY_NOT_TRUSTED: Public key not trusted',
    152: u'GPG_ERR_DECRYPT_FAILED: Decryption failed',
    153: u'GPG_ERR_KEY_EXPIRED: Key expired',
    154: u'GPG_ERR_SIG_EXPIRED: Signature expired',
    155: u'GPG_ERR_ENCODING_PROBLEM: Encoding problem',
    156: u'GPG_ERR_INV_STATE: Invalid state',
    157: u'GPG_ERR_DUP_VALUE: Duplicated value',
    158: u'GPG_ERR_MISSING_ACTION: Missing action',
    159: u'GPG_ERR_MODULE_NOT_FOUND: ASN.1 module not found',
    160: u'GPG_ERR_INV_OID_STRING: Invalid OID string',
    161: u'GPG_ERR_INV_TIME: Invalid time',
    162: u'GPG_ERR_INV_CRL_OBJ: Invalid CRL object',
    163: u'GPG_ERR_UNSUPPORTED_CRL_VERSION: Unsupported CRL version',
    164: u'GPG_ERR_INV_CERT_OBJ: Invalid certificate object',
    165: u'GPG_ERR_UNKNOWN_NAME: Unknown name',
    166: u'GPG_ERR_LOCALE_PROBLEM: A locale function failed',
    167: u'GPG_ERR_NOT_LOCKED: Not locked',
    168: u'GPG_ERR_PROTOCOL_VIOLATION: Protocol violation',
    169: u'GPG_ERR_INV_MAC: Invalid MAC',
    170: u'GPG_ERR_INV_REQUEST: Invalid request',
    171: u'GPG_ERR_UNKNOWN_EXTN: Unknown extension',
    172: u'GPG_ERR_UNKNOWN_CRIT_EXTN: Unknown critical extension',
    173: u'GPG_ERR_LOCKED: Locked',
    174: u'GPG_ERR_UNKNOWN_OPTION: Unknown option',
    175: u'GPG_ERR_UNKNOWN_COMMAND: Unknown command',
    176: u'GPG_ERR_NOT_OPERATIONAL: Not operational',
    177: u'GPG_ERR_NO_PASSPHRASE: No passphrase given',
    178: u'GPG_ERR_NO_PIN: No PIN given',
    179: u'GPG_ERR_NOT_ENABLED: Not enabled',
    180: u'GPG_ERR_NO_ENGINE: No crypto engine',
    181: u'GPG_ERR_MISSING_KEY: Missing key',
    182: u'GPG_ERR_TOO_MANY: Too many objects',
    183: u'GPG_ERR_LIMIT_REACHED: Limit reached',
    184: u'GPG_ERR_NOT_INITIALIZED: Not initialized',
    185: u'GPG_ERR_MISSING_ISSUER_CERT: Missing issuer certificate',
    186: u'GPG_ERR_NO_KEYSERVER: No keyserver available',
    187: u'GPG_ERR_INV_CURVE: Invalid elliptic curve',
    188: u'GPG_ERR_UNKNOWN_CURVE: Unknown elliptic curve',
    189: u'GPG_ERR_DUP_KEY: Duplicated key',
    190: u'GPG_ERR_AMBIGUOUS: Ambiguous result',
    191: u'GPG_ERR_NO_CRYPT_CTX: No crypto context',
    192: u'GPG_ERR_WRONG_CRYPT_CTX: Wrong crypto context',
    193: u'GPG_ERR_BAD_CRYPT_CTX: Bad crypto context',
    194: u'GPG_ERR_CRYPT_CTX_CONFLICT: Conflict in the crypto context',
    195: u'GPG_ERR_BROKEN_PUBKEY: Broken public key',
    196: u'GPG_ERR_BROKEN_SECKEY: Broken secret key',
    197: u'GPG_ERR_MAC_ALGO: Invalid MAC algorithm',
    198: u'GPG_ERR_FULLY_CANCELED: Operation fully cancelled',
    199: u'GPG_ERR_UNFINISHED: Operation not yet finished',
    200: u'GPG_ERR_BUFFER_TOO_SHORT: Buffer too short',
    201: u'GPG_ERR_SEXP_INV_LEN_SPEC: Invalid length specifier in S-expression',
    202: u'GPG_ERR_SEXP_STRING_TOO_LONG: String too long in S-expression',
    203: u'GPG_ERR_SEXP_UNMATCHED_PAREN: Unmatched parentheses in S-expression',
    204: u'GPG_ERR_SEXP_NOT_CANONICAL: S-expression not canonical',
    205: u'GPG_ERR_SEXP_BAD_CHARACTER: Bad character in S-expression',
    206: u'GPG_ERR_SEXP_BAD_QUOTATION: Bad quotation in S-expression',
    207: u'GPG_ERR_SEXP_ZERO_PREFIX: Zero prefix in S-expression',
    208: u'GPG_ERR_SEXP_NESTED_DH: Nested display hints in S-expression',
    209: u'GPG_ERR_SEXP_UNMATCHED_DH: Unmatched display hints',
    210: u'GPG_ERR_SEXP_UNEXPECTED_PUNC: Unexpected reserved punctuation in S-expression',
    211: u'GPG_ERR_SEXP_BAD_HEX_CHAR: Bad hexadecimal character in S-expression',
    212: u'GPG_ERR_SEXP_ODD_HEX_NUMBERS: Odd hexadecimal numbers in S-expression',
    213: u'GPG_ERR_SEXP_BAD_OCT_CHAR: Bad octal character in S-expression',
    217: u'GPG_ERR_SUBKEYS_EXP_OR_REV: All subkeys are expired or revoked',
    218: u'GPG_ERR_DB_CORRUPTED: Database is corrupted',
    219: u'GPG_ERR_SERVER_FAILED: Server indicated a failure',
    220: u'GPG_ERR_NO_NAME: No name',
    221: u'GPG_ERR_NO_KEY: No key',
    222: u'GPG_ERR_LEGACY_KEY: Legacy key',
    223: u'GPG_ERR_REQUEST_TOO_SHORT: Request too short',
    224: u'GPG_ERR_REQUEST_TOO_LONG: Request too long',
    225: u'GPG_ERR_OBJ_TERM_STATE: Object is in termination state',
    226: u'GPG_ERR_NO_CERT_CHAIN: No certificate chain',
    227: u'GPG_ERR_CERT_TOO_LARGE: Certificate is too large',
    228: u'GPG_ERR_INV_RECORD: Invalid record',
    229: u'GPG_ERR_BAD_MAC: The MAC does not verify',
    230: u'GPG_ERR_UNEXPECTED_MSG: Unexpected message',
    231: u'GPG_ERR_COMPR_FAILED: Compression or decompression failed',
    232: u'GPG_ERR_WOULD_WRAP: A counter would wrap',
    233: u'GPG_ERR_FATAL_ALERT: Fatal alert message received',
    234: u'GPG_ERR_NO_CIPHER: No cipher algorithm',
    235: u'GPG_ERR_MISSING_CLIENT_CERT: Missing client certificate',
    236: u'GPG_ERR_CLOSE_NOTIFY: Close notification received',
    237: u'GPG_ERR_TICKET_EXPIRED: Ticket expired',
    238: u'GPG_ERR_BAD_TICKET: Bad ticket',
    239: u'GPG_ERR_UNKNOWN_IDENTITY: Unknown identity',
    240: u'GPG_ERR_BAD_HS_CERT: Bad certificate message in handshake',
    241: u'GPG_ERR_BAD_HS_CERT_REQ: Bad certificate request message in handshake',
    242: u'GPG_ERR_BAD_HS_CERT_VER: Bad certificate verify message in handshake',
    243: u'GPG_ERR_BAD_HS_CHANGE_CIPHER: Bad change cipher message in handshake',
    244: u'GPG_ERR_BAD_HS_CLIENT_HELLO: Bad client hello message in handshake',
    245: u'GPG_ERR_BAD_HS_SERVER_HELLO: Bad server hello message in handshake',
    246: u'GPG_ERR_BAD_HS_SERVER_HELLO_DONE: Bad server hello done message in handshake',
    247: u'GPG_ERR_BAD_HS_FINISHED: Bad finished message in handshake',
    248: u'GPG_ERR_BAD_HS_SERVER_KEX: Bad server key exchange message in handshake',
    249: u'GPG_ERR_BAD_HS_CLIENT_KEX: Bad client key exchange message in handshake',
    250: u'GPG_ERR_BOGUS_STRING: Bogus string',
    251: u'GPG_ERR_FORBIDDEN: Forbidden',
    252: u'GPG_ERR_KEY_DISABLED: Key disabled',
    253: u'GPG_ERR_KEY_ON_CARD: Not possible with a card based key',
    254: u'GPG_ERR_INV_LOCK_OBJ: Invalid lock object',
    255: u'GPG_ERR_TRUE: True',
    256: u'GPG_ERR_FALSE: False',
    257: u'GPG_ERR_ASS_GENERAL: General IPC error',
    258: u'GPG_ERR_ASS_ACCEPT_FAILED: IPC accept call failed',
    259: u'GPG_ERR_ASS_CONNECT_FAILED: IPC connect call failed',
    260: u'GPG_ERR_ASS_INV_RESPONSE: Invalid IPC response',
    261: u'GPG_ERR_ASS_INV_VALUE: Invalid value passed to IPC',
    262: u'GPG_ERR_ASS_INCOMPLETE_LINE: Incomplete line passed to IPC',
    263: u'GPG_ERR_ASS_LINE_TOO_LONG: Line passed to IPC too long',
    264: u'GPG_ERR_ASS_NESTED_COMMANDS: Nested IPC commands',
    265: u'GPG_ERR_ASS_NO_DATA_CB: No data callback in IPC',
    266: u'GPG_ERR_ASS_NO_INQUIRE_CB: No inquire callback in IPC',
    267: u'GPG_ERR_ASS_NOT_A_SERVER: Not an IPC server',
    268: u'GPG_ERR_ASS_NOT_A_CLIENT: Not an IPC client',
    269: u'GPG_ERR_ASS_SERVER_START: Problem starting IPC server',
    270: u'GPG_ERR_ASS_READ_ERROR: IPC read error',
    271: u'GPG_ERR_ASS_WRITE_ERROR: IPC write error',
    273: u'GPG_ERR_ASS_TOO_MUCH_DATA: Too much data for IPC layer',
    274: u'GPG_ERR_ASS_UNEXPECTED_CMD: Unexpected IPC command',
    275: u'GPG_ERR_ASS_UNKNOWN_CMD: Unknown IPC command',
    276: u'GPG_ERR_ASS_SYNTAX: IPC syntax error',
    277: u'GPG_ERR_ASS_CANCELED: IPC call has been cancelled',
    278: u'GPG_ERR_ASS_NO_INPUT: No input source for IPC',
    279: u'GPG_ERR_ASS_NO_OUTPUT: No output source for IPC',
    280: u'GPG_ERR_ASS_PARAMETER: IPC parameter error',
    281: u'GPG_ERR_ASS_UNKNOWN_INQUIRE: Unknown IPC inquire',
    300: u'GPG_ERR_ENGINE_TOO_OLD: Crypto engine too old',
    301: u'GPG_ERR_WINDOW_TOO_SMALL: Screen or window too small',
    302: u'GPG_ERR_WINDOW_TOO_LARGE: Screen or window too large',
    303: u'GPG_ERR_MISSING_ENVVAR: Required environment variable not set',
    304: u'GPG_ERR_USER_ID_EXISTS: User ID already exists',
    305: u'GPG_ERR_NAME_EXISTS: Name already exists',
    306: u'GPG_ERR_DUP_NAME: Duplicated name',
    307: u'GPG_ERR_TOO_YOUNG: Object is too young',
    308: u'GPG_ERR_TOO_OLD: Object is too old',
    309: u'GPG_ERR_UNKNOWN_FLAG: Unknown flag',
    310: u'GPG_ERR_INV_ORDER: Invalid execution order',
    311: u'GPG_ERR_ALREADY_FETCHED: Already fetched',
    312: u'GPG_ERR_TRY_LATER: Try again later',
    313: u'GPG_ERR_WRONG_NAME: Wrong name',
    314: u'GPG_ERR_NO_AUTH: Not authenticated',
    315: u'GPG_ERR_BAD_AUTH: Bad authentication',
    316: u'GPG_ERR_NO_KEYBOXD: No Keybox daemon running',
    317: u'GPG_ERR_KEYBOXD: Keybox daemon error',
    318: u'GPG_ERR_NO_SERVICE: Service is not running',
    319: u'GPG_ERR_SERVICE: Service error',
    666: u'GPG_ERR_SYSTEM_BUG: System bug detected',
    711: u'GPG_ERR_DNS_UNKNOWN: Unknown DNS error',
    712: u'GPG_ERR_DNS_SECTION: Invalid DNS section',
    713: u'GPG_ERR_DNS_ADDRESS: Invalid textual address form',
    714: u'GPG_ERR_DNS_NO_QUERY: Missing DNS query packet',
    715: u'GPG_ERR_DNS_NO_ANSWER: Missing DNS answer packet',
    716: u'GPG_ERR_DNS_CLOSED: Connection closed in DNS',
    717: u'GPG_ERR_DNS_VERIFY: Verification failed in DNS',
    718: u'GPG_ERR_DNS_TIMEOUT: DNS Timeout',
    721: u'GPG_ERR_LDAP_GENERAL: General LDAP error',
    722: u'GPG_ERR_LDAP_ATTR_GENERAL: General LDAP attribute error',
    723: u'GPG_ERR_LDAP_NAME_GENERAL: General LDAP name error',
    724: u'GPG_ERR_LDAP_SECURITY_GENERAL: General LDAP security error',
    725: u'GPG_ERR_LDAP_SERVICE_GENERAL: General LDAP service error',
    726: u'GPG_ERR_LDAP_UPDATE_GENERAL: General LDAP update error',
    727: u'GPG_ERR_LDAP_E_GENERAL: Experimental LDAP error code',
    728: u'GPG_ERR_LDAP_X_GENERAL: Private LDAP error code',
    729: u'GPG_ERR_LDAP_OTHER_GENERAL: Other general LDAP error',
    750: u'GPG_ERR_LDAP_X_CONNECTING: LDAP connecting failed (X)',
    751: u'GPG_ERR_LDAP_REFERRAL_LIMIT: LDAP referral limit exceeded',
    752: u'GPG_ERR_LDAP_CLIENT_LOOP: LDAP client loop',
    754: u'GPG_ERR_LDAP_NO_RESULTS: No LDAP results returned',
    755: u'GPG_ERR_LDAP_CONTROL_NOT_FOUND: LDAP control not found',
    756: u'GPG_ERR_LDAP_NOT_SUPPORTED: Not supported by LDAP',
    757: u'GPG_ERR_LDAP_CONNECT: LDAP connect error',
    758: u'GPG_ERR_LDAP_NO_MEMORY: Out of memory in LDAP',
    759: u'GPG_ERR_LDAP_PARAM: Bad parameter to an LDAP routine',
    760: u'GPG_ERR_LDAP_USER_CANCELLED: User cancelled LDAP operation',
    761: u'GPG_ERR_LDAP_FILTER: Bad LDAP search filter',
    762: u'GPG_ERR_LDAP_AUTH_UNKNOWN: Unknown LDAP authentication method',
    763: u'GPG_ERR_LDAP_TIMEOUT: Timeout in LDAP',
    764: u'GPG_ERR_LDAP_DECODING: LDAP decoding error',
    765: u'GPG_ERR_LDAP_ENCODING: LDAP encoding error',
    766: u'GPG_ERR_LDAP_LOCAL: LDAP local error',
    767: u'GPG_ERR_LDAP_SERVER_DOWN: Cannot contact LDAP server',
    768: u'GPG_ERR_LDAP_SUCCESS: LDAP success',
    769: u'GPG_ERR_LDAP_OPERATIONS: LDAP operations error',
    770: u'GPG_ERR_LDAP_PROTOCOL: LDAP protocol error',
    771: u'GPG_ERR_LDAP_TIMELIMIT: Time limit exceeded in LDAP',
    772: u'GPG_ERR_LDAP_SIZELIMIT: Size limit exceeded in LDAP',
    773: u'GPG_ERR_LDAP_COMPARE_FALSE: LDAP compare false',
    774: u'GPG_ERR_LDAP_COMPARE_TRUE: LDAP compare true',
    775: u'GPG_ERR_LDAP_UNSUPPORTED_AUTH: LDAP authentication method not supported',
    776: u'GPG_ERR_LDAP_STRONG_AUTH_RQRD: Strong(er) LDAP authentication required',
    777: u'GPG_ERR_LDAP_PARTIAL_RESULTS: Partial LDAP results+referral received',
    778: u'GPG_ERR_LDAP_REFERRAL: LDAP referral',
    779: u'GPG_ERR_LDAP_ADMINLIMIT: Administrative LDAP limit exceeded',
    780: u'GPG_ERR_LDAP_UNAVAIL_CRIT_EXTN: Critical LDAP extension is unavailable',
    781: u'GPG_ERR_LDAP_CONFIDENT_RQRD: Confidentiality required by LDAP',
    782: u'GPG_ERR_LDAP_SASL_BIND_INPROG: LDAP SASL bind in progress',
    784: u'GPG_ERR_LDAP_NO_SUCH_ATTRIBUTE: No such LDAP attribute',
    785: u'GPG_ERR_LDAP_UNDEFINED_TYPE: Undefined LDAP attribute type',
    786: u'GPG_ERR_LDAP_BAD_MATCHING: Inappropriate matching in LDAP',
    787: u'GPG_ERR_LDAP_CONST_VIOLATION: Constraint violation in LDAP',
    788: u'GPG_ERR_LDAP_TYPE_VALUE_EXISTS: LDAP type or value exists',
    789: u'GPG_ERR_LDAP_INV_SYNTAX: Invalid syntax in LDAP',
    800: u'GPG_ERR_LDAP_NO_SUCH_OBJ: No such LDAP object',
    801: u'GPG_ERR_LDAP_ALIAS_PROBLEM: LDAP alias problem',
    802: u'GPG_ERR_LDAP_INV_DN_SYNTAX: Invalid DN syntax in LDAP',
    803: u'GPG_ERR_LDAP_IS_LEAF: LDAP entry is a leaf',
    804: u'GPG_ERR_LDAP_ALIAS_DEREF: LDAP alias dereferencing problem',
    815: u'GPG_ERR_LDAP_X_PROXY_AUTH_FAIL: LDAP proxy authorization failure (X)',
    816: u'GPG_ERR_LDAP_BAD_AUTH: Inappropriate LDAP authentication',
    817: u'GPG_ERR_LDAP_INV_CREDENTIALS: Invalid LDAP credentials',
    818: u'GPG_ERR_LDAP_INSUFFICIENT_ACC: Insufficient access for LDAP',
    819: u'GPG_ERR_LDAP_BUSY: LDAP server is busy',
    820: u'GPG_ERR_LDAP_UNAVAILABLE: LDAP server is unavailable',
    821: u'GPG_ERR_LDAP_UNWILL_TO_PERFORM: LDAP server is unwilling to perform',
    822: u'GPG_ERR_LDAP_LOOP_DETECT: Loop detected by LDAP',
    832: u'GPG_ERR_LDAP_NAMING_VIOLATION: LDAP naming violation',
    833: u'GPG_ERR_LDAP_OBJ_CLS_VIOLATION: LDAP object class violation',
    834: u'GPG_ERR_LDAP_NOT_ALLOW_NONLEAF: LDAP operation not allowed on non-leaf',
    835: u'GPG_ERR_LDAP_NOT_ALLOW_ON_RDN: LDAP operation not allowed on RDN',
    836: u'GPG_ERR_LDAP_ALREADY_EXISTS: Already exists (LDAP)',
    837: u'GPG_ERR_LDAP_NO_OBJ_CLASS_MODS: Cannot modify LDAP object class',
    838: u'GPG_ERR_LDAP_RESULTS_TOO_LARGE: LDAP results too large',
    839: u'GPG_ERR_LDAP_AFFECTS_MULT_DSAS: LDAP operation affects multiple DSAs',
    844: u'GPG_ERR_LDAP_VLV: Virtual LDAP list view error',
    848: u'GPG_ERR_LDAP_OTHER: Other LDAP error',
    881: u'GPG_ERR_LDAP_CUP_RESOURCE_LIMIT: Resources exhausted in LCUP',
    882: u'GPG_ERR_LDAP_CUP_SEC_VIOLATION: Security violation in LCUP',
    883: u'GPG_ERR_LDAP_CUP_INV_DATA: Invalid data in LCUP',
    884: u'GPG_ERR_LDAP_CUP_UNSUP_SCHEME: Unsupported scheme in LCUP',
    885: u'GPG_ERR_LDAP_CUP_RELOAD: Reload required in LCUP',
    886: u'GPG_ERR_LDAP_CANCELLED: LDAP cancelled',
    887: u'GPG_ERR_LDAP_NO_SUCH_OPERATION: No LDAP operation to cancel',
    888: u'GPG_ERR_LDAP_TOO_LATE: Too late to cancel LDAP',
    889: u'GPG_ERR_LDAP_CANNOT_CANCEL: Cannot cancel LDAP',
    890: u'GPG_ERR_LDAP_ASSERTION_FAILED: LDAP assertion failed',
    891: u'GPG_ERR_LDAP_PROX_AUTH_DENIED: Proxied authorization denied by LDAP',
    1500: u'GPG_ERR_SQL_OK: SQL success',
    1501: u'GPG_ERR_SQL_ERROR: SQL error',
    1502: u'GPG_ERR_SQL_INTERNAL: Internal logic error in SQL library',
    1503: u'GPG_ERR_SQL_PERM: Access permission denied (SQL)',
    1504: u'GPG_ERR_SQL_ABORT: SQL abort was requested',
    1505: u'GPG_ERR_SQL_BUSY: SQL database file is locked',
    1506: u'GPG_ERR_SQL_LOCKED: An SQL table in the database is locked',
    1507: u'GPG_ERR_SQL_NOMEM: SQL library ran out of core',
    1508: u'GPG_ERR_SQL_READONLY: Attempt to write a readonly SQL database',
    1509: u'GPG_ERR_SQL_INTERRUPT: SQL operation terminated by interrupt',
    1510: u'GPG_ERR_SQL_IOERR: I/O error during SQL operation',
    1511: u'GPG_ERR_SQL_CORRUPT: SQL database disk image is malformed',
    1512: u'GPG_ERR_SQL_NOTFOUND: Unknown opcode in SQL file control',
    1513: u'GPG_ERR_SQL_FULL: Insertion failed because SQL database is full',
    1514: u'GPG_ERR_SQL_CANTOPEN: Unable to open the SQL database file',
    1515: u'GPG_ERR_SQL_PROTOCOL: SQL database lock protocol error',
    1516: u'GPG_ERR_SQL_EMPTY: (internal SQL code: empty)',
    1517: u'GPG_ERR_SQL_SCHEMA: SQL database schema changed',
    1518: u'GPG_ERR_SQL_TOOBIG: String or blob exceeds size limit (SQL)',
    1519: u'GPG_ERR_SQL_CONSTRAINT: SQL abort due to constraint violation',
    1520: u'GPG_ERR_SQL_MISMATCH: Data type mismatch (SQL)',
    1521: u'GPG_ERR_SQL_MISUSE: SQL library used incorrectly',
    1522: u'GPG_ERR_SQL_NOLFS: SQL library uses unsupported OS features',
    1523: u'GPG_ERR_SQL_AUTH: Authorization denied (SQL)',
    1524: u'GPG_ERR_SQL_FORMAT: (unused SQL code: format)',
    1525: u'GPG_ERR_SQL_RANGE: SQL bind parameter out of range',
    1526: u'GPG_ERR_SQL_NOTADB: File opened that is not an SQL database file',
    1527: u'GPG_ERR_SQL_NOTICE: Notifications from SQL logger',
    1528: u'GPG_ERR_SQL_WARNING: Warnings from SQL logger',
    1600: u'GPG_ERR_SQL_ROW: SQL has another row ready',
    1601: u'GPG_ERR_SQL_DONE: SQL has finished executing',
    16381: u'GPG_ERR_MISSING_ERRNO: System error w/o errno',
    16382: u'GPG_ERR_UNKNOWN_ERRNO: Unknown system error',
    16383: u'GPG_ERR_EOF: End of file',
}
