#!/bin/sh

cd `dirname $0`/..

echo bin/duplicity > po/POTFILES.in
echo bin/rdiffdir >> po/POTFILES.in
find duplicity -name '*.py' >> po/POTFILES.in

find testing -name '*.py' > po/POTFILES.skip

cd `dirname $0`

intltool-update --pot -g duplicity
sed -i -e 's/^#\. TRANSL:/#./' duplicity.pot
